name: Build Electron App

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    paths:
      - .github/workflows/build.yml
      - src/**
      - patches/**
      - resources/**
      - package.json
      - tsconfig.json
      - pnpm-lock.yaml
      - tsconfig.web.json
      - tsconfig.node.json
      - pnpm-workspace.yaml
      - electron-builder.yml
      - electron.vite.config.ts
    branches: [ master, release ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            build: "linux"
          - os: macos-latest
            build: "mac"
          - os: windows-latest
            build: "win"

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
          run_install: false

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Install linux deps
        if: matrix.build == 'linux'
        run: |
          sudo apt update
          sudo apt install -y --install-recommends libarchive-tools

      - name: Install pacman tools
        if: matrix.build == 'linux'
        uses: termux-pacman/pacman-actions@v2.5

      - name: Install Dependencies and sync svelte-kit
        run: |
          pnpm install --frozen-lockfile
          pnpm sync:sveltekit

      - name: Build for ${{ matrix.build }}
        run: pnpm run build:${{ matrix.build }} --publish never
        env:
          MAIN_VITE_LAST_FM_API_KEY: ${{ secrets.LAST_FM_API_KEY }}
          MAIN_VITE_LAST_FM_SHARED_SECRET: ${{ secrets.LAST_FM_SHARED_SECRET }}
          MAIN_VITE_DISCORD_CLIENT_ID: ${{ secrets.DISCORD_CLIENT_ID }}

      - name: Create package db
        if: matrix.build == 'linux'
        run: |
          cd dist
          repo-add synara.db.tar.gz *.pacman
          cp synara.db.tar.gz synara.db

      - name: Upload Artifacts
        uses: actions/upload-artifact@v6
        with:
          name: synara-build-${{ matrix.build }}
          path: |
              dist/
              !dist/builder-debug.yml
              !dist/builder-effective-config.yaml
          retention-days: 1

  release:
    name: Create GitHub Release
    needs: [build]
    runs-on: ubuntu-latest
    env:
      CHANNEL_NAME: ${{ github.ref_name == 'master' && 'dev-desktop' || 'desktop' }}
      PRE_RELEASE: ${{ github.ref_name == 'master' }}
      TAG_SUFFIX: ${{ github.ref_name == 'master' && '-dev' || '' }}-desktop
      RELEASE_SUFFIX: ${{ github.ref_name == 'master' && ' (Development Build)' || '' }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Download all build artifacts
        uses: actions/download-artifact@v7
        with:
          merge-multiple: 'true'
          path: dist

      - name: Install jq
        run: sudo snap install jq yq

      - name: Collect Assets and Version
        id: collect_final_assets
        shell: bash
        run: |
          PKG_FILE=$(find . -type f -name 'package.json' -not -path '*/node_modules/*' -not -path '*/src/*' -not -path '*/dist/*' | head -n 1)

          if [ -z "$PKG_FILE" ]; then
            echo "::error::package.json not found in artifacts."
            exit 1
          fi

          RELEASE_VERSION=$(cat "$PKG_FILE" | jq -r '.version')
          echo "RELEASE_VERSION=$RELEASE_VERSION" >> $GITHUB_OUTPUT

      - name: Merge yml files
        shell: bash
        run: |
          LINUX_YML="dist/latest-linux.yml"
          MAC_YML="dist/latest-mac.yml"
          WIN_YML="dist/latest.yml"
          OUTPUT_FILE="dist/${{ env.CHANNEL_NAME }}.yml"

          CORE_DATA=$(yq -o=json '. | {"version": .version, "path": .path, "sha512": .sha512, "releaseDate": .releaseDate}' "$LINUX_YML" | jq -sR .)

          ALL_FILES=$(yq -o=json '.files' "$LINUX_YML" "$MAC_YML" "$WIN_YML" | jq -s 'flatten')
          FINAL_JSON=$(echo "$CORE_DATA" | jq -s '.[0] | fromjson | .files = ('"$ALL_FILES"')')

          echo "$FINAL_JSON" | yq -P > "$OUTPUT_FILE"
          echo "âœ… Consolidated metadata saved to $OUTPUT_FILE"

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.collect_final_assets.outputs.RELEASE_VERSION }}${{ env.TAG_SUFFIX }}
          name: Release v${{ steps.collect_final_assets.outputs.RELEASE_VERSION }}${{ env.RELEASE_SUFFIX }}
          repository: DerTyp7214/synara
          generate_release_notes: false
          prerelease: ${{ env.PRE_RELEASE }}
          target_commitish: desktop
          files: |
            dist/${{ env.CHANNEL_NAME }}.yml
            dist/synara.db
            dist/synara.db.tar.gz
            dist/synara-*
        env:
          GITHUB_TOKEN: ${{ secrets.SYNARA_GITHUB_TOKEN }}

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest${{ env.TAG_SUFFIX }}
          name: Release v${{ steps.collect_final_assets.outputs.RELEASE_VERSION }}${{ env.RELEASE_SUFFIX }}
          repository: DerTyp7214/synara
          generate_release_notes: false
          prerelease: ${{ env.PRE_RELEASE }}
          target_commitish: desktop
          files: |
            dist/${{ env.CHANNEL_NAME }}.yml
            dist/synara.db
            dist/synara.db.tar.gz
            dist/synara-*
        env:
          GITHUB_TOKEN: ${{ secrets.SYNARA_GITHUB_TOKEN }}
