name: Build Electron App

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - master
      - release
  pull_request:
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            build: "linux"
          - os: macos-latest
            build: "mac"
          - os: ubuntu-latest
            build: "win"

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
          run_install: false

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ matrix.build }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ matrix.build }}-pnpm-store-

      - name: Cache APT Packages
        uses: actions/cache@v4
        if: matrix.build == 'win'
        with:
          path: |
            /var/cache/apt/archives/**
            !/var/cache/apt/archives/lock
            !/var/cache/apt/archives/lock/**
            !/var/cache/apt/archives/partial
            !/var/cache/apt/archives/partial/**
          key: ${{ matrix.build }}-apt-cache-winehq-noble
          restore-keys: |
            ${{ matrix.build }}-apt-cache-

      - name: Install WineHQ (Stable for Noble)
        if: matrix.build == 'win'
        run: |
          sudo dpkg --add-architecture i386

          sudo mkdir -pm755 /etc/apt/keyrings
          sudo wget -O /etc/apt/keyrings/winehq-archive.key https://dl.winehq.org/wine-builds/winehq.key

          sudo wget -O /etc/apt/sources.list.d/winehq-noble.sources https://dl.winehq.org/wine-builds/ubuntu/dists/noble/winehq-noble.sources

          sudo apt update
          sudo apt install -y --install-recommends winehq-stable

      - name: Install Dependencies and sync svelte-kit
        shell: bash
        run: |
          pnpm install --frozen-lockfile
          pnpm sync:sveltekit

      - name: Build for ${{ matrix.build }}
        shell: bash
        run: pnpm run build:${{ matrix.build }}

      - name: Move files
        shell: bash
        if: matrix.build == 'linux'
        run: |
          mkdir upload
          mv dist/*.AppImage upload/synara-desktop.AppImage
          mv dist/*.deb upload/synara-desktop.deb

      - name: Move files
        shell: bash
        if: matrix.build == 'win'
        run: |
          mkdir upload
          mv dist/*.exe upload/synara-desktop.exe

      - name: Move files
        shell: bash
        if: matrix.build == 'mac'
        run: |
          mkdir upload
          mv dist/*.dmg upload/synara-desktop.dmg

      - name: Upload Selective Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.build }}-release-assets
          overwrite: 'true'
          retention-days: 1
          path: |
            upload/*
            ${{ matrix.build == 'linux' && 'package.json' || '' }}

  release:
    name: Create GitHub Release
    needs: [build]
    runs-on: ubuntu-latest

    steps:
      - name: Download all build artifacts
        uses: actions/download-artifact@v5
        with:
          pattern: '*-release-assets'
          merge-multiple: 'true'
          path: assets

      - name: Install jq
        run: sudo snap install jq

      - name: Collect Assets and Version
        id: collect_final_assets
        shell: bash
        run: |
          sudo chown -R $USER:$USER assets
          sudo chmod -R a+r assets
          PKG_FILE=$(find assets -type f -name 'package.json' | head -n 1)

          if [ -z "$PKG_FILE" ]; then
            echo "::error::package.json not found in artifacts."
            exit 1
          fi

          RELEASE_VERSION=$(cat "$PKG_FILE" | jq -r '.version')
          echo "RELEASE_VERSION=$RELEASE_VERSION" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.collect_final_assets.outputs.RELEASE_VERSION }}${{ github.ref_name == 'master' && '-dev' || '' }}-desktop
          name: Release v${{ steps.collect_final_assets.outputs.RELEASE_VERSION }}${{ github.ref_name == 'master' && ' (Development Build)' || '' }}
          repository: DerTyp7214/synara
          generate_release_notes: false
          prerelease: ${{ github.ref_name == 'master' }}
          target_commitish: desktop
          files: |
            assets/**
            !assets/package.json
        env:
          GITHUB_TOKEN: ${{ secrets.SYNARA_GITHUB_TOKEN }}


      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest${{ github.ref_name == 'master' && '-dev' || '' }}-desktop
          name: Release v${{ steps.collect_final_assets.outputs.RELEASE_VERSION }}${{ github.ref_name == 'master' && ' (Development Build)' || '' }}
          repository: DerTyp7214/synara
          generate_release_notes: false
          prerelease: ${{ github.ref_name == 'master' }}
          target_commitish: desktop
          files: |
            assets/**
            !assets/package.json
        env:
          GITHUB_TOKEN: ${{ secrets.SYNARA_GITHUB_TOKEN }}
