name: Build Electron App

on:
  push:
    branches:
      - master
      - release
  pull_request:
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            build: "linux"
          - os: macos-latest
            build: "mac"
          - os: ubuntu-latest
            build: "win"

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
          run_install: false

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.build }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.build }}-pnpm-store-

      - name: Install Dependencies and sync svelte-kit
        shell: bash
        run: |
          pnpm install --frozen-lockfile
          pnpm sync:sveltekit

      - name: Build for ${{ matrix.build }}
        shell: bash
        run: pnpm run build:${{ matrix.build }}

      - name: Install yq for Linux YAML parsing
        if: runner.os == 'Linux'
        run: sudo snap install yq

      - name: Install wine for Windows build
        if: runner.build == 'win'
        run: sudo snap install wine

      - name: Identify and Output Required Assets (Linux)
        if: runner.build == 'linux'
        id: asset_finder_linux
        shell: bash
        run: |
          echo "ASSET_PATHS=$(yq '(.files[] | "dist/" + .url)' "dist/latest-linux.yml" | tr '\n' ' ' | tr -d '"')" >> $GITHUB_OUTPUT

      - name: Identify and Output Required Assets (Windows)
        if: runner.build == 'win'
        id: asset_finder_windows
        shell: bash
        run: |
          echo "ASSET_PATHS=$(yq '(.files[] | "dist/" + .url)' "dist/latest.yml" | tr '\n' ' ' | tr -d '"')" >> $GITHUB_OUTPUT

      - name: Identify and Output Required Assets (macOS)
        if: runner.build == 'mac'
        id: asset_finder_macos
        shell: bash
        run: |
          echo "ASSET_PATHS=$(find dist -type f -name "*.dmg" | tr '\n' ' ')" >> $GITHUB_OUTPUT

      - name: Upload Selective Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ runner.os }}-release-assets
          overwrite: 'true'
          path: |
            package.json
            ${{ runner.build == 'linux' && steps.asset_finder_linux.outputs.ASSET_PATHS || '' }}
            ${{ runner.build == 'mac' && steps.asset_finder_macos.outputs.ASSET_PATHS || '' }}
            ${{ runner.build == 'win' && steps.asset_finder_windows.outputs.ASSET_PATHS || '' }}

  release:
    name: Create GitHub Release
    needs: [build]
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Download all build artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: '*-release-assets'
          path: assets

      - name: Install jq
        run: sudo snap install jq

      - name: Collect Assets and Version
        id: collect_final_assets
        shell: bash
        run: |
          PKG_FILE=$(find assets -type f -name 'package.json' | head -n 1)

          if [ -z "$PKG_FILE" ]; then
            echo "::error::package.json not found in artifacts."
            exit 1
          fi

          RELEASE_VERSION=$(jq -r '.version' "$PKG_FILE")
          echo "RELEASE_VERSION=$RELEASE_VERSION" >> $GITHUB_OUTPUT

          ASSET_FILES=$(find assets -type f ! -name 'package.json' | tr '\n' ' ')
          echo "ASSET_FILES=$ASSET_FILES" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.collect_final_assets.outputs.RELEASE_VERSION }}
          generate_release_notes: true
          files: ${{ steps.collect_final_assets.outputs.ASSET_FILES }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
